#!/bin/sh

mpd ~/.config/mpd/mpd.conf &  # music daemon

xsetroot -cursor_name left_ptr &  # shape of arrow

gcin &  # chinese input

dunst &  # notify daemon

echo "power on" | bluetoothctl &


# personal shell script
# notify &  # all system notify

# monitorDetect &  # monitor arrange


exec xmonad # window manager




