#!/bin/sh

mpd ~/.config/mpd/mpd.conf &  # music daemon

picom -b --config ~/.config/picom/picom.conf --experimental-backends &  # handle opacity

xsetroot -cursor_name left_ptr &  # shape of arrow

gcin &  # chinese input

dunst &  # notify daemon

#monitorDetect &  # monitor arrange

notify &  # all system notify

nitrogen --restore &  # wallpaper

#echo "power on" | bluetoothctl &


exec xmonad # window manager




