#!/bin/sh


# export path variable
export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.config/rofi/bin":$PATH
export PATH="/opt/miniconda3/bin":$PATH
export PATH="$HOME/Document/ntu_hw/introduction-to-computer/nand2tetris/tools/":$PATH





#default program
export EDITOR="nvim"
export VISUAL="nvim"
export TERMINAL="alacritty"
export BROWSER="waterfox"
export _JAVA_AWT_WM_NONREPARENTING=1
export JULIA_DEPOT_PATH="$XDG_DATA_HOME/julia:$JULIA_DEPOT_PATH"

# chinese input
export LANG="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export XMODIFIERS="@im=gcin"
export GCIN_XIM="gcin"
export GTK_IM_MODULE="gcin"
export QT_IM_MODULE="gcin"


# ~/ Clean-up
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
# disable filej
export LESSHISTFILE=-
# fix path
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
export XAUTHORITY="$XDG_CONFIG_HOME/X11/xauthority"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export ZDOTDIR="$HOME/.config/zsh"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/config.toml"
export STARSHIP_CACHE="$XDG_CACHE_HOME/starship/"
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"
export SSB_HOME="$XDG_DATA_HOME/zoom"
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch/notmuchrc"
export NMBGIT="$XDG_DATA_HOME/notmuch/nmbug"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
#export _JAVA_OPTIONS=-
#Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export WINEARCH=win64
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
